// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Recipe
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject recipeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Recipe";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Description("Description"),
		Ingredients("Ingredients"),
		Categories("Categories"),
		Steps("Steps"),
		Contains("MyFirstModule.Contains");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Recipe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Recipe"));
	}

	protected Recipe(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject recipeMendixObject)
	{
		if (recipeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Recipe", recipeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Recipe");

		this.recipeMendixObject = recipeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Recipe.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Recipe initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Recipe.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Recipe initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Recipe(context, mendixObject);
	}

	public static myfirstmodule.proxies.Recipe load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Recipe.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Recipe> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Recipe> result = new java.util.ArrayList<myfirstmodule.proxies.Recipe>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Recipe" + xpathConstraint))
			result.add(myfirstmodule.proxies.Recipe.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Ingredients
	 */
	public final java.lang.String getIngredients()
	{
		return getIngredients(getContext());
	}

	/**
	 * @param context
	 * @return value of Ingredients
	 */
	public final java.lang.String getIngredients(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Ingredients.toString());
	}

	/**
	 * Set value of Ingredients
	 * @param ingredients
	 */
	public final void setIngredients(java.lang.String ingredients)
	{
		setIngredients(getContext(), ingredients);
	}

	/**
	 * Set value of Ingredients
	 * @param context
	 * @param ingredients
	 */
	public final void setIngredients(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ingredients)
	{
		getMendixObject().setValue(context, MemberNames.Ingredients.toString(), ingredients);
	}

	/**
	 * @return value of Categories
	 */
	public final java.lang.String getCategories()
	{
		return getCategories(getContext());
	}

	/**
	 * @param context
	 * @return value of Categories
	 */
	public final java.lang.String getCategories(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Categories.toString());
	}

	/**
	 * Set value of Categories
	 * @param categories
	 */
	public final void setCategories(java.lang.String categories)
	{
		setCategories(getContext(), categories);
	}

	/**
	 * Set value of Categories
	 * @param context
	 * @param categories
	 */
	public final void setCategories(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String categories)
	{
		getMendixObject().setValue(context, MemberNames.Categories.toString(), categories);
	}

	/**
	 * @return value of Steps
	 */
	public final java.lang.String getSteps()
	{
		return getSteps(getContext());
	}

	/**
	 * @param context
	 * @return value of Steps
	 */
	public final java.lang.String getSteps(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Steps.toString());
	}

	/**
	 * Set value of Steps
	 * @param steps
	 */
	public final void setSteps(java.lang.String steps)
	{
		setSteps(getContext(), steps);
	}

	/**
	 * Set value of Steps
	 * @param context
	 * @param steps
	 */
	public final void setSteps(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String steps)
	{
		getMendixObject().setValue(context, MemberNames.Steps.toString(), steps);
	}

	/**
	 * @return value of Contains
	 */
	public final myfirstmodule.proxies.RecipeList getContains() throws com.mendix.core.CoreException
	{
		return getContains(getContext());
	}

	/**
	 * @param context
	 * @return value of Contains
	 */
	public final myfirstmodule.proxies.RecipeList getContains(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.RecipeList result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Contains.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.RecipeList.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Contains
	 * @param contains
	 */
	public final void setContains(myfirstmodule.proxies.RecipeList contains)
	{
		setContains(getContext(), contains);
	}

	/**
	 * Set value of Contains
	 * @param context
	 * @param contains
	 */
	public final void setContains(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.RecipeList contains)
	{
		if (contains == null)
			getMendixObject().setValue(context, MemberNames.Contains.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Contains.toString(), contains.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return recipeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Recipe that = (myfirstmodule.proxies.Recipe) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Recipe";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
