// This file was generated by Mendix Modeler 7.18.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the MyFirstModule module
	public static myfirstmodule.proxies.RecipeDetails getRecipeByName(IContext context, myfirstmodule.proxies.Recipe _recipe)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Recipe", _recipe == null ? null : _recipe.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "MyFirstModule.GetRecipeByName", params);
			return result == null ? null : myfirstmodule.proxies.RecipeDetails.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<myfirstmodule.proxies.Recipe> recipeListMF(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.List<IMendixObject> objs = Core.execute(context, "MyFirstModule.RecipeListMF", params);
			java.util.List<myfirstmodule.proxies.Recipe> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<myfirstmodule.proxies.Recipe>();
				for (IMendixObject obj : objs)
					result.add(myfirstmodule.proxies.Recipe.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void updateRecipe(IContext context, myfirstmodule.proxies.RecipeDetails _recipeDetails)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("RecipeDetails", _recipeDetails == null ? null : _recipeDetails.getMendixObject());
			Core.execute(context, "MyFirstModule.UpdateRecipe", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}